version: "3.9"
services:
  db_postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: proyecto_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
